language: java

before_install:
  - mkdir -p $HOME/.m2

addons:
  sonarcloud:
    organization: "danielemariano"
    token:
      secure: "NVEh+0uWqeVyjNSfjNyvQfWmXkeQOOikky+0cKD54OstrsoXtp1Dk2l7scDKG0YMbYv45pXq+xQo8rOD+VKg8VNZl/tXFk75SGIPBTkD2wnz/xeOra3yAwEK34DvJarxwq6CWukz/biNIsRDhiJtidHx+qOBjCV7b1XYH8d/jMaAPAl0pTOw6VKxskX/6EX/BMIn0o7+donLGK0YUhYmZTY3Vs8aqlLwrGS/UgXWSq/GTwQSI/Cesczev8QkZn4ax4xo4bOy31VNsotWITt6a3Xf41g46+5ATKC0zHfGYkgtaqP7E6S4Oez+AWxU/vxSewM/0BWPPZ5VxfW6GbjaZbkfiQzKVq80qQSszq2/wA125+1dB3LDkAbvnpmSvrKUrqhDCMToJDmba0VTwd6FYPg1aa3QvgxquGYesSlh62T2aOHEpVIv+6PPn+ShO96TSb6ygGIrmNcMSRdt/MQEkh3Zqwa1x2cEX7wBnbC72t3ZS+YEzQpiZcozvRTiSGqDlMZxP4Qnw/txm33h9AYkQTYHkRKlb6j3N/0LCysB7+ubDUKWq914408uj+xK2kmtrpP5PIoO2zAvgUN4W+Lg9rzydCbzA/GGphKpN/Y8rxBDd8tSKYqpggVw5DTHjPztvm3ucdh+2vm9P+27TWHXSgfWuZiw9LnAgPlTZ5GxBf0="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=danielemariano_openJPA-test
  #- mvn clean verify sonar:sonar -Dsonar.projectKey=danielemariano_openJPA-test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=danielemariano_openJPA-test && cd openjpa-jdbc && mvn org.pitest:pitest-maven:mutationCoverage surefire:test -Dtest=QualifiedDBIdentifierSetPathTest
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=danielemariano_openJPA-test && cd openjpa-jdbc && mvn org.pitest:pitest-maven:mutationCoverage surefire:test -Dtest=QualifiedDBIdentifierSplitPathTest
