addons:
  sonarcloud:
    organization: "danielemariano"
    token:
      secure: "rXMNHLB28Xr4yTSvDDtGU/ge1lCtVvdsI73EOPW8E7UfgRT+uvRUyieCMCszrcXdEit6k6Fu4HKgiOss3uBr+IuGH9VXHsHT0S3hmPEs8LI78iCWpwXoGl25MorOyFQSaCLqQDJV00Mj5yxN2bxlq13OhrD/8Ju/O94fTLgX20kxcb3pomXtU3aJNkze7ywrukRYN0MrexZIUfX+Q7rGtC1D+6h5N9QWYK5DkZfZAMPseDLkKMelxL/JW9g9ymrGkwKSU+ziyeim0mgHfX3wsEer7d3orb+RVfWd7VxHMvqwlYkfDPov64umhzVu0tzdP6h8SsWCyFtlJQvax90Jtt7XiaT1bxzI7erQAAV8FGycNQOKiknIwbFyQytDe+9rotcpctDLYj5SBnZ7AgtGuy0/KrjlqqYD3izt/9QixMb+exhFIul4zzJEfiuX6xnyhatDERT/F9otLgNhfaArn+IGyVnuS6BOdJxL300s5wjN18mKgH1O94K3zBTeBW77PoshK7OdhBIiVm3ILWRzwwIeTUxezu2g1L/pS2o0IK/KE6dxZo9WCUw4gKibK5XDbdyHYMeXkCEpP6KHcgFjcajj0aZiNdgSCoKRwIRyhBJ28qj6UMkDFa32UNltNIWq03iBwm9qt0moj9/p1b0Kk2ZZOFmksin3fFdmFtfbOGY=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=danielemariano_openJPA-test
